parameters:
#    blog.example.class: Sdz\BlogBundle\Example

services:
#    blog.example:
#        class: %blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
      sdz_blog.antispam:
        class: Sdz\BlogBundle\Antispam\SdzAntispam
        arguments: [$mailer, %locale%, 3]